In [52]:
import pickle
import numpy as np
import pandas as pd
from sklearn.model_selection import ShuffleSplit

In [11]:
# Depickle
pickle_in = open("data/train.pkl", "rb")
result = pickle.load(pickle_in)

array([[  27.42765666, 3335.78295109],
       [  -4.96183456, 2647.40265244],
       [ -27.86119551,  520.73369536],
       ...,
       [  27.54602153, 1729.42858449],
       [   8.97475985, 1264.43870071],
       [ -19.66451461,  -54.2662792 ]])

In [76]:
# Convert to numpy array and display the first 5 elements
train_data = np.array(result)
train_data[:5]

array([[ 2.74276567e+01,  3.33578295e+03],
       [-4.96183456e+00,  2.64740265e+03],
       [-2.78611955e+01,  5.20733695e+02],
       [-1.53463398e+01,  3.51892491e+03],
       [ 2.86732690e+00, -3.21770068e+03]])

In [95]:
# Shuffle the dataset
np.random.shuffle(train_data)
train_data

array([[ 1.13691739e+01,  6.22955026e+02],
       [ 2.48860268e+00,  2.65959861e+03],
       [-1.29084222e+01,  2.05947150e+03],
       ...,
       [ 3.34719979e+01,  3.79993986e+03],
       [-2.30436421e+01,  3.10692467e+03],
       [ 2.66506377e+01,  1.89787775e+02]])

In [119]:
# Separate the dataset
print(len(train_data))
n = 16
print(n)
model = np.split(train_data, n)

8000
16


In [112]:
x = np.arange(24)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [113]:
np.split(x, 4)

[array([0, 1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17]),
 array([18, 19, 20, 21, 22, 23])]