In [52]:
import pickle
import numpy as np
import pandas as pd
from sklearn.model_selection import ShuffleSplit

In [11]:
# Depickle
pickle_in = open("data/train.pkl", "rb")
result = pickle.load(pickle_in)

array([[  27.42765666, 3335.78295109],
       [  -4.96183456, 2647.40265244],
       [ -27.86119551,  520.73369536],
       ...,
       [  27.54602153, 1729.42858449],
       [   8.97475985, 1264.43870071],
       [ -19.66451461,  -54.2662792 ]])

In [76]:
# Convert to numpy array and display the first 5 elements
train_data = np.array(result)
train_data[:5]
# print("Len: ", len(train_data))

array([[ 2.74276567e+01,  3.33578295e+03],
       [-4.96183456e+00,  2.64740265e+03],
       [-2.78611955e+01,  5.20733695e+02],
       [-1.53463398e+01,  3.51892491e+03],
       [ 2.86732690e+00, -3.21770068e+03]])

In [77]:
# Shuffle the dataset
rs = ShuffleSplit(n_splits=16, test_size=0.2, random_state=0)
c = 1
for i in rs.split(train_data):
    print("Model", c)
    print("TRAIN:", i, "\tlen: ", len(i))
    print()
    c += 1

Model 1
TRAIN: (array([1001, 7360, 5234, ..., 1653, 2607, 2732]), array([3069, 1675, 6385, ..., 4096, 1595, 5023])) 	len:  2

Model 2
TRAIN: (array([1481, 1523, 5228, ..., 2253, 2026,  710]), array([2553,  547, 1894, ..., 3061, 7421, 5842])) 	len:  2

Model 3
TRAIN: (array([3857, 3520, 4116, ..., 7910,  689,  901]), array([2122, 7510,  762, ..., 1158, 6962, 6903])) 	len:  2

Model 4
TRAIN: (array([7956, 2150, 7484, ..., 5336, 6576, 4901]), array([2692, 6430,  828, ...,  450,  591, 1751])) 	len:  2

Model 5
TRAIN: (array([5890, 6691, 1025, ...,  112, 1607, 6846]), array([6724,  107,  873, ..., 5496, 6112, 3485])) 	len:  2

Model 6
TRAIN: (array([1669, 6025, 5046, ..., 7092,  189,  621]), array([6274, 3281,  288, ..., 3360, 6756, 2944])) 	len:  2

Model 7
TRAIN: (array([3811, 6460, 3876, ..., 7597,  622, 4615]), array([6823, 1614, 7888, ..., 7111, 2836,  278])) 	len:  2

Model 8
TRAIN: (array([1520,  537, 6334, ...,  129, 1303, 4862]), array([4220, 1294, 3736, ..., 1587,  346, 6609])) 	l

In [50]:
# Separate the data
X = train_data[:, 0]
y = train_data[:, 1]
X

array([ 32.38460378,  14.54813772,  15.50295278, ..., -14.77205043,
       -33.0026702 ,   3.01786005])